FACE_RECOGNITION_ENABLED = False
IDENTITY_TRACKING_ENABLED = False
TEMPORARY_TRACKING_IDS = True

ORIGINAL_EVIDENCE_ALLOWED = True
INVESTIGATION_REQUIRES_AUTHORIZATION = True
AUDIT_EVIDENCE_ACCESS = True